### ISSUE TITLE
Installation and dependencies

### ISSUE THREAD

**Issue by tadejm** [mezis/appfab#158]
Update the Readme with detailed installation and dependencies specification.
Describe how to install and run the appfab app in different environments.

For example:
- some specs fail if you don't have memcached running.
- maybe use foreman to start depended processes in dev env

**Comment by mezis** [comment]
> maybe use foreman to start depended processes in dev env

That's a good idea to mention in the README.
The app does use `dotenv-rails` directly, so at least `.env` will get loaded even if not using Foreman.

**Comment by thejspr** [comment]
I believe this was resolved in #170

**Comment by mezis** [comment]
Indeed, and I don't think it's up to the application to start infrastructure processes like the cache and the database.

Locally they should be setup and started automatically by Macports+Launchd (on Darwin) or Aptitude+Upstart (on Ubuntu) for instance, or otherwise be made available (e.g. Heroku addons).

Unfortunately there still is a Homebrew fad going on and Homebrew doesn't set up services properly :smiling_imp:
